### ISSUE TITLE
Error with chrome-extension

### ISSUE THREAD

**Issue by zevero** [Giorgio003/Youtube-TV#13]
I installed your fork, and I can see on the images loaded, that everything seems fine, but it fails in loading this

```
GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
```

I have no idea why!

**Comment by zevero** [comment]
I am sorry!
Everything is working fine - my div was just of height: 0;

The chrome-extension error is not related to this.

**Comment by Giorgio003** [comment]
Yup, the `chrome-extension` error is related to Chromecasts or just casting in general. I looked into it months ago and there was no progress or even a way to suppress the errors. 

Kind of annoying when troubleshooting however those same errors will show up on YouTube as well so hopefully Google will get around to fixing it one of these days.
