### ISSUE TITLE
Sort Playlist

### ISSUE THREAD

**Issue by zevero** [Giorgio003/Youtube-TV#15]
In my case all titles are in reverse ... is there some sorting possibility?

**Comment by Giorgio003** [comment]
Currently there is no sorting option... yet! 
The order displayed is currently the playlist order as appeared on YouTube so it is possible to re-order from there. 

However some cases you might not have access to re-order playlists so I will look to add additional sorting options such as: list reverse, sort by title and sort by uploaded date at first. Later I'll consider additional sorting options like shuffle, view count, etc. if there's interest in other sorting methods.

**Comment by zevero** [comment]
Thank you for mentioning the possibility to order a youtube playlist.
I was not able to order my channel. But I made a playlist with the correct order. Problem solved!

Sorting may be a nice enhancement but it would add complexity to this project.
I prefer ordering via youtube playlists, which is much easier.

**Comment by Giorgio003** [comment]
Added some basic sorting options (by upload, reverse, and shuffle) in my latest commit 12a0863938e9ca2a8fb716906c16616cb7f4b4d7.
If there are any other sorting methods you (or anyone) would prefer, let me know!
