### ISSUE TITLE
Error when using random youtube channel url, like 'UCsDl6A77CrbkSJLtxQFVDGw'

### ISSUE THREAD

**Issue by ghost** [Giorgio003/Youtube-TV#16]
error is "Uncaught TypeError: Cannot read property 'contentDetails' of undefined"
with custom urls like 'jackvalefilms' works ok
help me please

**Comment by Giorgio003** [comment]
For the channel ID was it specified as `channelId: 'UC...'` or `user: 'UC...'`?

Should work in either of the following configurations:
`channelId: 'UCsDl6A77CrbkSJLtxQFVDGw'`
or
`user: 'jackvalefilms'`

Unfortunately the new API has separated the previous username system from Channel ID's into 2 different fields. Currently I will push and update to clear up that confusion in the documentation.  
Additionally I will look into creating a system to detect between Channel ID's and Usernames in the same field to eliminate the separation from the start.

**Comment by ghost** [comment]
wow, so simple )) thank you very much !
